update
lethanhdat25/ledat-bunbu2 pull request #2
Opened 2021-12-10 15:41 UTC by lethanhdat25

xong task 1

2021-12-13 08:15 UTC, namnd0210 requested changes

2021-12-13 08:15 UTC, namnd0210 commented on backend/routes/bunbu.js
> +module.exports=router;
Thêm endline

2021-12-13 08:15 UTC, namnd0210 commented on backend/routes/index.js
> +module.exports=route;
Thêm endline

2021-12-13 08:15 UTC, namnd0210 commented on backend/routes/victory.js
> +module.exports=router;
Thêm endline

2021-12-13 08:15 UTC, namnd0210 commented on frontend/src/Component/Task1.js
> +export default Task1;
Thêm endline

2021-12-13 08:15 UTC, namnd0210 commented on frontend/src/App.js
> +      <Task1/>
ví dụ là: DeviceSummary

2021-12-13 08:15 UTC, namnd0210 commented on backend/index.js
>  app.listen(port,()=>console.log("SERVER IS RUNNING..."));
Thêm endline

2021-12-13 08:15 UTC, namnd0210 commented on backend/routes/index.js
> +    app.use("/",bunbuRouter);
Đặt tên có ý nghĩa với chức năng đang làm đi em

2021-12-13 08:15 UTC, namnd0210 commented
Thêm cho anh ảnh chụp màn hình hiển thị pie chart vào trong mô tả của PR nhé

2021-12-15 07:03 UTC, hoangdai95 approved these changes

2021-12-15 07:05 UTC, namnd0210 approved these changes

2021-12-15 07:05 UTC, merged